name: aral_mezunlar_mobile
description: Aral Mezunlar Dernegi Projesi.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  persistent_bottom_nav_bar: ^5.0.2
  getwidget: ^4.0.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.14
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  another_flushbar: ^1.12.30
  firebase_storage: ^11.4.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  flutter_native_splash: ^1.3.0
  whatsapp_unilink: ^2.1.0
  firebase_messaging: ^14.7.4
  permission_handler: ^11.0.1
  crypto: ^3.0.3
  firebase_app_check: ^0.2.1+5
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  audioplayers: ^5.2.1
  google_nav_bar: ^5.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/aral.png
    - lib/assets/authbackground.jpg
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
     - family: Manrope
       fonts:
         - asset: lib/assets/Manrope-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #